apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
    credendials : |
      [default]
      aws_access_key_id = ASIASZZLOO6OBU2J6CNC
      aws_secret_access_key = 6V5Dd6PSjNDvlXDxJA5U4+GaAOwE99Mhee02e0+s
      aws_session_token = FwoGZXIvYXdzEI///////////wEaDBV6jCiAI1N3ko+LJyLVASJehoAHR43zlWgh3V7aUGTpr/iluG+PFPiOIAC0bREvlYN+JtWwnjk9QEG/wx7zqq28nEO27LCPE4Ag86ZN+tbIuwUIqz+Mk3ZSZwQmyGyCuavkdwbAHdD5aMQKpj1IYyVYyKioK/AkT1N2bSdCfGQUIOHdmGxX3FyD+9Atqe4wq5BNMoY9drJWKS/0dmv98/t5YTFYA4cmIk3OVcFPl8tUVmo2GnAsOaDHS54dSRKp4CwgHpdZZE1l4/XNXu5cwBXqWppmM+O7BbAslHNn1yrfAo8cSyjHoouaBjItlVv89rbXqKdFI+nid2QWtZv7lzTrU7SF/Od/H2tAhKSekasCwlFWLPWjBksF